### ISSUE TITLE
Kudos on having svgo by default

### ISSUE THREAD

**Issue by DrummerHead** [eugene1g/font-blast#5]
Just wanna say thanks for already passing the SVGs through SVGO.

I downloaded svgo, passed it and saw "0%" improvements and I was like "wtf". Checked the original source and was like "Well, this looks too good to be true"; checked package.json of this project and saw svgo sitting there :D good call!

**Comment by eugene1g** [comment]
Thank you for the kind words Drummer :)

I accidentally published this package into a public repo, and somehow it became useful to people. Sadly I don't have the time to run it against any currently popular fonts to see if it still works, or try to integrate other relevant projects instead of doing SVG math in this lib. But if it currently works for you, I'm happy about that!
